// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVD2l5P6w8VEqAXLHG3b1sc-WnEEjDdKs',
    appId: '1:353004129332:web:8e97f599a42d5a20cd0e61',
    messagingSenderId: '353004129332',
    projectId: 'trippo-463109',
    authDomain: 'trippo-463109.firebaseapp.com',
    storageBucket: 'trippo-463109.firebasestorage.app',
    measurementId: 'G-TT003LJXRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOma_ot39-NA5zqQIK6arsds8M1fclLcg',
    appId: '1:353004129332:android:2eeed3e277c85700cd0e61',
    messagingSenderId: '353004129332',
    projectId: 'trippo-463109',
    storageBucket: 'trippo-463109.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY9HKMtNxWtz3V2Dv84A6ERFMNuRBKYzk',
    appId: '1:353004129332:ios:63c31570164d408dcd0e61',
    messagingSenderId: '353004129332',
    projectId: 'trippo-463109',
    storageBucket: 'trippo-463109.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY9HKMtNxWtz3V2Dv84A6ERFMNuRBKYzk',
    appId: '1:353004129332:ios:63c31570164d408dcd0e61',
    messagingSenderId: '353004129332',
    projectId: 'trippo-463109',
    storageBucket: 'trippo-463109.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVD2l5P6w8VEqAXLHG3b1sc-WnEEjDdKs',
    appId: '1:353004129332:web:96026cff100dee02cd0e61',
    messagingSenderId: '353004129332',
    projectId: 'trippo-463109',
    authDomain: 'trippo-463109.firebaseapp.com',
    storageBucket: 'trippo-463109.firebasestorage.app',
    measurementId: 'G-MYTK5E0FGP',
  );
}
